### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'weights'

### ISSUE THREAD

**Issue by CharisWg** [sovit-123/fasterrcnn-pytorch-training-pipeline#119]
Building model from scratch...
Traceback (most recent call last):
  File "train.py", line 571, in <module>
    main(args)
  File "train.py", line 306, in main
    model = build_model(num_classes=NUM_CLASSES, pretrained=True)
  File "/datashare3/charis/code/recaps/fasterRcnn/fasterrcnn-pytorch-training-pipeline-main/models/create_fasterrcnn_model.py", line 6, in return_fasterrcnn_resnet50_fpn
    model = fasterrcnn_resnet50_fpn.create_model(
  File "/datashare3/charis/code/recaps/fasterRcnn/fasterrcnn-pytorch-training-pipeline-main/models/fasterrcnn_resnet50_fpn.py", line 7, in create_model
    model = torchvision.models.detection.fasterrcnn_resnet50_fpn(
  File "/datashare3/charis/anaconda/envs/m2/lib/python3.8/site-packages/torchvision/models/detection/faster_rcnn.py", line 368, in fasterrcnn_resnet50_fpn
    model = FasterRCNN(backbone, num_classes, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'weights'

**Comment by sovit-123** [comment]
Hi. May I know your PyTorch version? This seems to be an issue with older PyTorch versions. The library supports PyTorch 1.12.0 and higher.

**Comment by CharisWg** [comment]
My PyTorch version is 1.9

**Comment by sovit-123** [comment]
Okay. I think updating the PyTorch version to 1.12.0 or higher will solve the issue.

**Comment by sovit-123** [comment]
Hi. I hope your issue has been solved. I am closing the issue for now. Please reopen if necessary.
