### ISSUE TITLE
KeyError: ‘fasterrcnn_resnet50’

### ISSUE THREAD

**Issue by samahwaleed** [sovit-123/fasterrcnn-pytorch-training-pipeline#30]
I am trying to run the code on my custom dataset but I got this error.

```
Building model from scratch...
Traceback (most recent call last):
  File "train.py", line 491, in <module>
    main(args)
  File "train.py", line 248, in main
    build_model = create_model[args['model']]
KeyError: 'fasterrcnn_resnet50'
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
wandb: Synced smoke_training: https://wandb.ai/samahwa/fastercnn-pytorch-training-pipeline/runs/ejy5jyw8
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20221128_113545-ejy5jyw8/logs
```

**Comment by sovit-123** [comment]
@samahwaleed 
The model key should be `fasterrcnn_resnet50_fpn`. I have updated the key in the code but need to update the README file as well. 
Will do as as soon as possible.
