### ISSUE TITLE
how can I bypass wandb?

### ISSUE THREAD

**Issue by dev2y** [sovit-123/fasterrcnn-pytorch-training-pipeline#47]
Wanted to train smoke and my setup went fine.. I tried the following and I am getting the following...
Is there a way to skip creating W&B account?

```
python train.py --config data_configs/smoke.yaml --epochs 100 --model fasterrcnn_resnet50_fpn --project-name smoke_training --batch-size 16
Not using distributed mode
wandb: (1) Create a W&B account
wandb: (2) Use an existing W&B account
wandb: (3) Don't visualize my results
wandb: Enter your choice:

```

**Comment by sovit-123** [comment]
@dev2y 
Type 3 and press the Enter (return) key

**Comment by dev2y** [comment]
Thanks.. I went ahead and created an account.. But I am now getting this error.
Is this because I am trying to train using CPU but it says `device cuda` below?

```
Not using distributed mode
wandb: Currently logged in as: dev26 (dbo). Use `wandb login --relogin` to force relogin
wandb: Tracking run with wandb version 0.13.10
wandb: Run data is saved locally in /home//rcnn/fastercnn-pytorch-training-pipeline/wandb/run-20230214_000245-fgan9pge
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run smoke_training
wandb: ⭐️ View project at https://wandb.ai/dbo/fastercnn-pytorch-training-pipeline
wandb: 🚀 View run at https://wandb.ai/dbo/fastercnn-pytorch-training-pipeline/runs/fgan9pge
device cuda
Creating data loaders
Traceback (most recent call last):
  File "/home//rcnn/fastercnn-pytorch-training-pipeline/train.py", line 532, in <module>
    main(args)
  File "/fastercnn-pytorch-training-pipeline/train.py", line 248, in main
    train_sampler = RandomSampler(train_dataset)
  File "/home/rcnn/pyenv/lib/python3.10/site-packages/torch/utils/data/sampler.py", line 107, in __init__
    raise ValueError("num_samples should be a positive integer "
ValueError: num_samples should be a positive integer value, but got num_samples=0
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
wandb: 🚀 View run smoke_training at: https://wandb.ai/dbo/fastercnn-pytorch-training-pipeline/runs/fgan9pge
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20230214_000245-fgan9pge/logs
```

**Comment by sovit-123** [comment]
@dev2y  
Can you try the `--disable-wandb` with the `train.py` command and let me know?
The above looks like a version issue.

**Comment by dev2y** [comment]
Hi @sovit-123, thank you. Paths to data in `data_confg` were incorrect.

Looks like I am good to train now but it is looking for graphics driver. I don't have a GPU and wondering how I can fall back to CPU. 

```
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
```

**Comment by sovit-123** [comment]
@dev2y 
CUDA warning will be there, but you won't face any errors. It will train as it should in the CPU.

**Comment by dev2y** [comment]
Thank you. Will close this.
